apiVersion: v1
kind: ConfigMap
data:
  config.json: |
    {
      "ServerConfigs": [
        {
        "Type": "HTTP",
        "Port": 8080
        },
        {
        "Type": "PROMETHEUS",
        "Port": 8080
        }
      ],
      "EndpointConfigs": {}
    }
metadata:
  name: kawe-configmap
  namespace: default