apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 3
  labels:
    app: kawe
  name: kawe
  namespace: qdak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kawe
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kawe
    spec:
      containers:
      - image: tothbence9922/kawe:latest
        imagePullPolicy: Always
        name: kawe
        ports:
        - containerPort: 80
          name: 80tcp
          protocol: TCP
      restartPolicy: Always
      serviceAccount: kawe-account
      serviceAccountName: kawe-account
