apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: kawe
  name: kawe
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kawe-account
  namespace: kawe
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kawe
  name: kawe-resource-reader
rules:
- apiGroups: [""]
  resources: ["services", "pods", "namespaces", "endpoints"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kawe-resource-reader
subjects:
  - kind: ServiceAccount
    # Reference to ServiceAccount kind's `metadata.name`
    name: kawe-account
    # Reference to ServiceAccount kind's `metadata.namespace`
    namespace: kawe
roleRef:
  kind: ClusterRole
  name: kawe-resource-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 3
  labels:
    app: kawe
  name: kawe
  namespace: kawe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kawe
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kawe
    spec:
      containers:
      - image: tothbence9922/kawe:latest
        imagePullPolicy: Always
        name: kawe
        ports:
        - containerPort: 80
          name: 80tcp
          protocol: TCP
      restartPolicy: Always
      serviceAccount: kawe-account
      serviceAccountName: kawe-account
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kawe.periodicity: "5000"
    kawe.processor.threshold: "50"
    kawe.processor.type: percentage
  name: kawe-service
  namespace: kawe
spec:
  ports:
  - name: tcp80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kawe
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: kawe-ingress
  namespace: kawe
spec:
  rules:
  - host: kawe.datatronic.hu
    http:
      paths:
      - backend:
          service:
            name: kawe-service
            port:
              number: 80
        path: /api/v1/services
        pathType: Prefix
---
