apiVersion: v1
kind: ServiceAccount
metadata:
  name: kawe-account
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: kawe-resource-reader
rules:
- apiGroups: [""]
  resources: ["services", "pods", "namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kawe-resource-reader
subjects:
  - kind: ServiceAccount
    # Reference to ServiceAccount kind's `metadata.name`
    name: kawe-account
    # Reference to ServiceAccount kind's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: kawe-resource-reader
  apiGroup: rbac.authorization.k8s.io